variables:
  DOCKER_REGISTRY: 264617996336.dkr.ecr.eu-west-2.amazonaws.com
  AWS_DEFAULT_REGION: eu-west-2
  APP_NAME: flask-app
  DOCKER_HOST: tcp://docker:2375

publish:
  image:
    name: amazon/aws-cli
    entrypoint: [""] 
  services:
    - docker:dind
  before_script:
    - amazon-linux-extras install docker
    - aws --version
    - docker --version
  script:
    - docker build -t $DOCKER_REGISTRY/$APP_NAME:$CI_JOB_ID .
    - aws ecr get-login-password | docker login --username AWS --password-stdin $DOCKER_REGISTRY
    - docker push $DOCKER_REGISTRY/$APP_NAME:$CI_JOB_ID

